Highcharts.chart('container', {
    chart: {
        type: 'packedbubble',
        height: '90%'
    },
    title: {
        text: 'Top 50 Highest Scored Posts per Subreddit',
        align: 'center'
    },
tooltip: {
  useHTML: true,
  pointFormat: '<b>{point.name}:</b><br/><b>Score:</b> {point.score}<br/>Click on bubble to go to post'
},
plotOptions: {
  packedbubble: {
    minSize: '20%',
    maxSize: '100%',
    zMin: 0,
    zMax: 100000,
    layoutAlgorithm: {
      gravitationalConstant: 0.05,
      splitSeries: true,
      seriesInteraction: false,
      dragBetweenSeries: true,
      parentNodeLimit: true
    },
    dataLabels: {
      enabled: false,
      format: '{point.name}',
      filter: {
        property: 'y',
        operator: '>',
        value: 250
      },
      style: {
        color: 'black',
        textOutline: 'none',
        fontWeight: 'normal'
      }
    },
    point: {
      events: {
        click: function() {
          window.open(this.url, '_blank');
        }
      }
    }
  }
},
    series: [{'name': 'Conservative',
  'data': [{'name': 'For those of you comparing these protests to Boston 1773  take a look at these pictures and tell me how this is patriotic to you  That is The Capitol Building',
    'value': 110685,
    'score': 110685,
    'url': 'https://www.reddit.com/gallery/krxl6t'},
   {'name': 'Fox News  McConnell believes Trump committed impeachable offenses  supports Democrats  impeachment efforts',
    'value': 48994,
    'score': 48994,
    'url': 'https://www.foxnews.com/politics/mcconnell-believes-trump-committed-impeachable-offenses-supports-democrats-impeachment-efforts-report'},
   {'name': 'House impeaches Trump for second time over Capitol riots',
    'value': 45677,
    'score': 45677,
    'url': 'http://www.breakingthenews.net/news/details/54323954'},
   {'name': 'New SEC Rule  Wall Street Will Now Only Allow Traders Who Wear A Top Hat And Monocle And Carry Around Giant Bags Of Money',
    'value': 44190,
    'score': 44190,
    'url': 'https://babylonbee.com/news/wall-street-bans-anyone-who-doesnt-wear-a-top-hat-and-carry-around-giant-bags-of-money'},
   {'name': 'Washington Post Reports Trump  Pressured  Georgia Secretary Of State To  Find  Votes',
    'value': 37749,
    'score': 37749,
    'url': 'https://www.dailywire.com/news/washington-post-reports-trump-pressured-georgia-secretary-of-state-to-find-votes'},
   {'name': 'Can t argue with that logic',
    'value': 37099,
    'score': 37099,
    'url': 'https://i.redd.it/ouxqia215i191.jpg'},
   {'name': 'Republican Starting To Think Trump Might Not Pull Off A Last Minute 4D Chess Move',
    'value': 36019,
    'score': 36019,
    'url': 'https://babylonbee.com/news/republican-starting-to-think-trump-might-not-pull-off-a-last-minute-3d-chess-move'},
   {'name': 'Romney rips Trump over Capitol Hill mayhem   This is what the president has caused',
    'value': 34009,
    'score': 34009,
    'url': 'https://www.washingtonexaminer.com/news/romney-rips-trump-over-capitol-hill-mayhem-this-is-what-the-president-has-caused'},
   {'name': 'And he s not the only one',
    'value': 32291,
    'score': 32291,
    'url': 'https://i.redd.it/q507th72c0l61.png'},
   {'name': 'M kay',
    'value': 31075,
    'score': 31075,
    'url': 'https://i.redd.it/p36f1vkk82p61.jpg'},
   {'name': 'Potential red wave turns into trickle in disappointing midterm elections for Republicans',
    'value': 30068,
    'score': 30068,
    'url': 'https://www.foxnews.com/politics/potential-red-wave-turns-trickle-disappointing-midterm-elections-republicans'},
   {'name': 'Joe IMMEDIATELY rips up Trump s legacy  New President will STOP building border wall  order federal mask mandate  scrap  Muslim  ban  rejoin climate accord and dissolve anti woke 1776 Commission',
    'value': 29743,
    'score': 29743,
    'url': 'https://www.dailymail.co.uk/news/article-9167281/Bidens-act-orders-pandemic-climate-immigration.html'},
   {'name': 'Parents begged police for upward of 40 minutes to stop Texas school shooter  Report',
    'value': 27430,
    'score': 27430,
    'url': 'https://www.washingtonexaminer.com/news/parents-begged-police-for-upwards-of-40-minutes-to-stop-texas-school-shooter-report'},
   {'name': 'found on r wholesomememes',
    'value': 25190,
    'score': 25190,
    'url': 'https://i.redd.it/0vlwic1t2lb61.jpg'},
   {'name': 'Poll  Nearly Two Thirds of Americans Want a Third Party to Represent Their Interests',
    'value': 22276,
    'score': 22276,
    'url': 'https://www.westernjournal.com/poll-support-third-party-america-reaches-time-high/'},
   {'name': 'Oppression from the Villa',
    'value': 22127,
    'score': 22127,
    'url': 'https://i.redd.it/jggny4kre0m61.png'},
   {'name': 'It s Time For Americans To Refuse To Trade With Slaveholders    Now that we know  beyond a doubt  of China s abhorrent treatment of the Uighurs we must reconsider our relations with the Slave Power rising in the East',
    'value': 21040,
    'score': 21040,
    'url': 'https://thefederalist.com/2021/03/15/its-time-for-americans-to-refuse-to-trade-with-slaveholders/'},
   {'name': 'Biden pardoning all prior federal offenses of simple marijuana possession',
    'value': 20731,
    'score': 20731,
    'url': 'https://www.foxnews.com/politics/biden-pardoning-all-prior-federal-offenses-simple-marijuana-possession'},
   {'name': 'After Being Kicked Off Social Media  Trump Forced To Go Door To Door And Shout  RIGGED ELECTION',
    'value': 20575,
    'score': 20575,
    'url': 'https://babylonbee.com/news/after-being-kicked-off-social-media-trump-forced-to-go-door-to-door-and-shout-rigged-election'},
   {'name': 'Sen  Cruz reintroduces amendment imposing term limits on members of Congress',
    'value': 20319,
    'score': 20319,
    'url': 'https://www.cbs7.com/2021/01/25/sen-cruz-reintroduces-amendment-imposing-term-limits-on-members-of-congress/'},
   {'name': 'Capitol rioters could face up to 10 years in prison under Trump monument executive order',
    'value': 19934,
    'score': 19934,
    'url': 'https://www.foxnews.com/politics/capitol-rioters-prison-trump-executive-order-federal'},
   {'name': 'Happy Birthday to this American hero',
    'value': 19892,
    'score': 19892,
    'url': 'https://i.imgur.com/J7D2yW9.jpg'},
   {'name': 'McConnell says Trump provoked Jan  6 riot',
    'value': 19359,
    'score': 19359,
    'url': 'http://www.breakingthenews.net/news/details/54371888'},
   {'name': 'Google deletes 100 000 negative reviews of Robinhood App',
    'value': 18734,
    'score': 18734,
    'url': 'https://gizmodo.com/google-deletes-100-000-negative-reviews-of-robinhood-ap-1846156699'},
   {'name': 'Biden s inaugural parade is canceled and replaced with a virtual version to avoid drawing large crowds amid the pandemic',
    'value': 18416,
    'score': 18416,
    'url': 'https://www.dailymail.co.uk/news/article-9109493/Biden-inauguration-feature-virtual-nationwide-parade.html'},
   {'name': 'Nevada Sen  Cortez Masto keeps critical seat  defeating GOP challenger Adam Laxalt',
    'value': 18212,
    'score': 18212,
    'url': 'https://mynews4.com/news/election/nevada-senator-catherine-cortez-masto-keeps-critical-seat-defeating-gop-challenger-adam-laxalt-election-las-veags-reno-election'},
   {'name': 'Somethings we can agree on',
    'value': 18202,
    'score': 18202,
    'url': 'https://www.reddit.com/gallery/l7g5ei'},
   {'name': 'Exit Poll  Generation Z  Millennials Break Big for Democrats  63  vs  35  for Republicans',
    'value': 17701,
    'score': 17701,
    'url': 'https://www.breitbart.com/midterm-election/2022/11/09/exit-poll-generation-z-millennials-break-big-for-democrats/'},
   {'name': 'Joe Biden sworn in as 46th U S  president',
    'value': 16594,
    'score': 16594,
    'url': 'https://www.foxnews.com/politics/live-updates-inauguration-1-20-21'},
   {'name': 'May 35th  1989   the Chinese Communist Party slaughters their own citizens   protestors and bystanders alike   after weeks of massive pro Democracy protests',
    'value': 16584,
    'score': 16584,
    'url': 'https://i.imgur.com/4GETV4d.jpg'},
   {'name': 'It s Time For Mitch McConnell To Go',
    'value': 16433,
    'score': 16433,
    'url': 'https://amgreatness.com/2021/01/07/its-time-for-mitch-to-go/'},
   {'name': 'BREAKING  Derek Chauvin Guilty On All 3 Counts In George Floyd s Death',
    'value': 16386,
    'score': 16386,
    'url': 'https://minnesota.cbslocal.com/2021/04/20/derek-chauvin-guilty-verdict-george-floyd-death-trial/'},
   {'name': 'Trump being investigated for Espionage Act violation  unsealed FBI warrant shows',
    'value': 15793,
    'score': 15793,
    'url': 'https://www.washingtonexaminer.com/news/justice/trump-investigated-espionage-act-violation-unsealed-fbi-warrant'},
   {'name': 'Supreme Court rules warrantless home gun confiscation is unconstitutional in 9 0 vote',
    'value': 14857,
    'score': 14857,
    'url': 'https://americanmilitarynews.com/2021/05/supreme-court-rules-warrantless-home-gun-confiscation-is-unconstitutional-in-9-0-vote/'},
   {'name': 'Your terms are acceptable',
    'value': 14466,
    'score': 14466,
    'url': 'https://i.redd.it/16gdp3sgl9d81.jpg'},
   {'name': 'Democrat Katie Hobbs Wins Arizona Governor s Race  Defeating Kari Lake',
    'value': 14392,
    'score': 14392,
    'url': 'https://www.latestly.com/socially/world/breaking-democrat-katie-hobbs-wins-arizona-governors-race-defeating-kari-lake-nbc-latest-tweet-by-bno-news-live-4459869.html'},
   {'name': 'After a lot of research  it appears that their excuse for this is closing the income and generational wealth gap between whites  minorities and  undocumented migrants',
    'value': 14287,
    'score': 14287,
    'url': 'https://i.redd.it/rgjsrgq3oep61.jpg'},
   {'name': 'It s time we start pushing for term limits in Congress',
    'value': 13895,
    'score': 13895,
    'url': 'http://www.termlimits.com'},
   {'name': 'Twitter permanently bans Donald Trump',
    'value': 13259,
    'score': 13259,
    'url': 'https://www.theverge.com/2021/1/8/22218753/twitter-bans-trump-permanently-realdonaldtrump?utm_campaign=theverge&amp;utm_content=chorus&amp;utm_medium=social&amp;utm_source=twitter'},
   {'name': 'Man Who Carries Smartphone Everywhere He Goes Worried Government Might Track Him Through Vaccine',
    'value': 12778,
    'score': 12778,
    'url': 'https://babylonbee.com/news/the-government-can-track-you-through-the-vaccine-says-man-who-has-carried-around-smartphone-since-2009'},
   {'name': 'U S  Ready To Evacuate Ukraine President Zelensky So He s Not Captured Or Killed  He Refuses To Go',
    'value': 12768,
    'score': 12768,
    'url': 'https://www.dailywire.com/news/u-s-ready-to-evacuate-ukraine-president-zelensky-so-hes-not-captured-or-killed-he-refuses-to-go'},
   {'name': 'Bill to ban biological men from women s sports gains bipartisan support in Congress',
    'value': 12687,
    'score': 12687,
    'url': 'https://campusreform.org/article?id=16497'},
   {'name': 'The passengers of United 93 are American Heroes',
    'value': 12361,
    'score': 12361,
    'url': 'https://i.imgur.com/L3s3FXw.jpg'},
   {'name': 'Bill Barr Urges Republicans to Pick an  Impressive  and  Younger  2024 Nominee Instead of Trump',
    'value': 12348,
    'score': 12348,
    'url': 'https://www.nationalreview.com/corner/bill-barr-urges-republicans-to-pick-an-impressive-and-younger-2024-nominee-instead-of-trump/amp/'},
   {'name': 'Biden Voter On CNN   They re Dropping Bombs In Syria And Those Bombs Are Pretty Expensive For A Guy Who Owes Me   2 000   VIDEO',
    'value': 12257,
    'score': 12257,
    'url': 'https://www.usasupreme.com/biden-voter-on-cnn-theyre-dropping-bombs-in-syria-and-those-bombs-are-pretty-expensive-for-a-guy-who-owes-me-2000-video/'},
   {'name': 'So  this is acceptable',
    'value': 12209,
    'score': 12209,
    'url': 'https://i.redd.it/x5rmktghgyy61.png'},
   {'name': 'Nancy Pelosi s Husband Seems to be a Savant at Timing His Stock Market Trades  Beating Nearly Every Hedge Fund by 30',
    'value': 12133,
    'score': 12133,
    'url': 'https://politics.retalk.com/nancy-pelosis-husband-seems-to-be-a-savant-at-timing-his-stock-market-trades-beating-nearly-every-hedge-fund-by-30'},
   {'name': 'BREAKING  Russia Begins Full Scale Invasion Into Ukraine  Putin Confirms  Military Operation  Underway',
    'value': 11981,
    'score': 11981,
    'url': 'https://www.dailywire.com/news/breaking-russia-begins-full-scale-invasion-into-ukraine-putin-confirms-military-operation-underway'},
   {'name': 'Reddit bans r Donaldtrump for repeated violations following Capitol Hill riot',
    'value': 11614,
    'score': 11614,
    'url': 'https://www.cnet.com/news/reddit-bans-rdonaldtrump-for-repeated-violations-following-capitol-hill-riot/'},
   {'name': 'Trumps claimed negative income in four of six years between 2015 and 2020  report',
    'value': 11524,
    'score': 11524,
    'url': 'https://nypost.com/2022/12/21/trumps-claimed-negative-income-in-four-of-six-years-between-2015-2020-report/'}]},
 {'name': 'Liberal',
  'data': [{'name': "Republicans now 'shocked, shocked' that there's a deficit, HAHAHAHAHA HAHAHAHAHA HAHAHAHAHA the Republican Party folks",
    'value': 1127,
    'score': 1127,
    'url': 'https://www.msn.com/en-us/news/politics/republicans-now-shocked-shocked-that-theres-a-deficit/ar-BB1d91AL'},
   {'name': 'Pro-Trump Election Deniers Lose in Nebraska Republican Primaries',
    'value': 1074,
    'score': 1074,
    'url': 'https://www.bloomberg.com/news/articles/2022-05-11/candidates-backing-trump-2020-claims-lose-nebraska-primaries'},
   {'name': 'Most Americans support using the popular vote to decide U.S. presidents',
    'value': 969,
    'score': 969,
    'url': 'https://www.npr.org/2022/08/10/1116688726/most-americans-support-using-the-popular-vote-to-decide-u-s-presidents-data-show'},
   {'name': 'Report: QAnon Congresswoman Was Live-Tweeting Nancy Pelosi’s Location To Terrorists',
    'value': 967,
    'score': 967,
    'url': 'https://www.patheos.com/blogs/progressivesecularhumanist/2021/01/report-qanon-congresswoman-was-live-tweeting-nancy-pelosis-location-to-terrorists/'},
   {'name': 'GOP group launches billboards demanding Cruz and Hawley resign',
    'value': 922,
    'score': 922,
    'url': 'https://www.independent.co.uk/news/world/americas/us-politics/gop-cruz-hawley-billboards-trump-b1794894.html'},
   {'name': 'Joe Biden’s Done More Good in a Week Than Donald Trump Did in Four Years',
    'value': 912,
    'score': 912,
    'url': 'https://www.thedailybeast.com/joe-bidens-done-more-good-in-a-week-than-donald-trump-did-in-four-years'},
   {'name': "'I reported 7 to 8 guys': Sexy liberal woman joins conservative dating site, seduces several January 6 rioters into giving her their personal info, which she then forwards to the FBI",
    'value': 898,
    'score': 898,
    'url': ''},
   {'name': "Trump Reportedly 'Livid,' 'Screaming at Everyone' over Midterm Results",
    'value': 887,
    'score': 887,
    'url': 'https://people.com/politics/trump-reportedly-livid-screaming-after-midterm-election-results/?utm_campaign=peoplemagazine&amp;utm_content=new&amp;utm_medium=social&amp;utm_source=twitter.com&amp;utm_term=636bd7e88257d100016779a9'},
   {'name': 'Oh My Fucking God, Get the Fucking Vaccine Already, You Fucking Fucks',
    'value': 855,
    'score': 855,
    'url': 'https://www.mcsweeneys.net/articles/oh-my-fucking-god-get-the-fucking-vaccine-already-you-fucking-fucks'},
   {'name': 'The Republican Party Needs To Be Abolished, Now. They Don’t Care About Anyone’s Safety, They Don’t Care About Human Life. So Many Lives Would Be Saved If Republicans Were Just Gone.',
    'value': 846,
    'score': 846,
    'url': 'https://www.msnbc.com/msnbc/amp/rcna30497'},
   {'name': 'Rudy Giuliani Is Reportedly Close to Broke—and Donald Trump Isn’t Taking His Calls; That’s what happens when you go to bat for a notoriously cheap, friendless, crappy businessman.',
    'value': 819,
    'score': 819,
    'url': 'https://www.motherjones.com/politics/2021/08/rudy-giuliani-broke-trump-fundraising-legal-bills/'},
   {'name': 'Biden to kill Keystone XL pipeline extension on inauguration day',
    'value': 806,
    'score': 806,
    'url': 'https://www.ctvnews.ca/world/america-votes/biden-to-kill-keystone-xl-pipeline-extension-on-inauguration-day-1.5270600'},
   {'name': 'GOP removes page praising Donald Trump\'s "historic" peace deal with Taliban',
    'value': 800,
    'score': 800,
    'url': 'https://www.newsweek.com/gop-removes-webpage-praising-trumps-historic-peace-deal-taliban-1619605'},
   {'name': 'Pete Buttigieg congratulated for masterclass confirmation hearing as he’s set to be first openly gay cabinet member',
    'value': 797,
    'score': 797,
    'url': 'https://www.yahoo.com/news/pete-buttigieg-congratulated-masterclass-confirmation-183832264.html'},
   {'name': "Trump's Twitter ban hurt him more than losing the election to Biden, his niece Mary says",
    'value': 782,
    'score': 782,
    'url': 'https://www.businessinsider.com/trump-twitter-ban-hurt-more-losing-to-biden-niece-mary-2021-3'},
   {'name': 'Mike Lindell: Costco has stopped selling MyPillow products',
    'value': 780,
    'score': 780,
    'url': 'https://www.businessinsider.com/mike-lindell-mypillow-costco-stopped-selling-products-retailer-sales-2021-4?amp'},
   {'name': 'OAN parent company ordered to pay MSNBC, Rachel Maddow $250,000 after losing defamation lawsuit',
    'value': 778,
    'score': 778,
    'url': 'https://www.usatoday.com/story/entertainment/tv/2021/02/09/msnbc-rachel-maddow-awarded-legal-fees-after-oan-lawsuit/4447175001/'},
   {'name': 'The Trump presidency is over, and Obamacare is still alive: Trump managed to accomplish very little on health care, despite Republicans’ decade-long obsession with repealing the Affordable Care Act.',
    'value': 777,
    'score': 777,
    'url': 'https://www.vox.com/policy-and-politics/22238505/donald-trump-obamacare-joe-biden'},
   {'name': 'Biden Ousts All 10 of Trump’s Union Busters From Powerful Labor Panel',
    'value': 776,
    'score': 776,
    'url': 'https://slate.com/news-and-politics/2021/02/biden-fires-trump-union-busters-federal-service-impasses-panel.html'},
   {'name': 'Dems Should Sue Now To Stop Trump Run Under Constitution Insurrectionist Ban',
    'value': 773,
    'score': 773,
    'url': 'https://www.huffpost.com/entry/14th-amendment-constitution-insurrectionist-ban-trump-lawsuit-alan-morrison_n_62d49f2be4b0f6913031334b'},
   {'name': 'WE GOT THE SENATE',
    'value': 763,
    'score': 763,
    'url': 'https://www.reddit.com/r/Liberal/comments/ytqgz7/we_got_the_senate/'},
   {'name': 'Trump Jr wanted for questioning by DC attorney general over alleged inaugural funds abuse',
    'value': 742,
    'score': 742,
    'url': 'https://www.yahoo.com/news/trump-jr-wanted-questioning-dc-093935643.html'},
   {'name': "Judge: Kim Davis violated gay couples' rights by refusing marriage licenses : NPR",
    'value': 726,
    'score': 726,
    'url': 'https://www.npr.org/2022/03/19/1087723875/kim-davis-court-same-sex-marriage'},
   {'name': 'Bill Barr Reportedly Burns His Bridges in Scathing Tell All, Sounds Off on Trump’s ‘Erratic Personal Behavior’ and Blames Him for Jan. 6',
    'value': 720,
    'score': 720,
    'url': 'https://www.mediaite.com/trump/bill-barr-reportedly-burns-his-bridges-in-scathing-tell-all-sounds-off-on-trumps-erratic-personal-behavior-and-pettiness/'},
   {'name': 'Trump Will Be Deposed Under Oath Next Week, and You Know What Happens When Trumps Are Under Oath',
    'value': 713,
    'score': 713,
    'url': 'https://www.vanityfair.com/news/2021/10/donald-trump-under-oath-depositions'},
   {'name': 'White House backs bill to expand voting rights, curb gerrymandering',
    'value': 710,
    'score': 710,
    'url': 'https://thehill.com/homenews/administration/541028-white-house-backs-bill-to-expand-voting-rights-curb-gerrymandering'},
   {'name': "LeVar Burton Doubles Down After Conservatives Criticize Him For Calling Book Bans 'Bullsh*t' On 'The View'",
    'value': 707,
    'score': 707,
    'url': 'https://www.comicsands.com/levar-burton-book-bans-view-2657502475.html'},
   {'name': "Trump's White House blocked government websites aimed at helping Americans vote, fighting human trafficking, easing homelessness, and stopping fraud, federal records show",
    'value': 706,
    'score': 706,
    'url': 'https://www.businessinsider.com/donald-trump-website-government-white-house-president-omb-2022-11#amp_tf=From%20%251%24s&amp;aoh=16689656971858&amp;csi=0&amp;referrer=https%3A%2F%2Fwww.google.com&amp;ampshare=https%3A%2F%2Fwww.businessinsider.com%2Fdonald-trump-website-government-white-house-president-omb-2022-11'},
   {'name': "Ex-GOP Senator Calls Party a 'Cult,' Says Trump 'Poisoned' US Democracy: Book",
    'value': 706,
    'score': 706,
    'url': 'https://www.businessinsider.com/alan-simpson-trump-gop-cult-democracy-book-2022-7'},
   {'name': "Former White House chief of staff says he is in 'disbelief' over GOP support for Putin after Trump called the Russian leader a genius",
    'value': 704,
    'score': 704,
    'url': 'https://www.businessinsider.com/trump-chief-of-staff-john-kelly-says-disbelief-gop-support-putin-2022-2'},
   {'name': 'Opinion | The GOP is no longer a party. It’s a movement to impose White Christian nationalism.',
    'value': 700,
    'score': 700,
    'url': 'https://www.washingtonpost.com/opinions/2022/04/27/gop-no-longer-a-party-movement-impose-christian-nationalism/'},
   {'name': 'Democrats officially introduce impeachment article, Republican forces vote on 25th Amendment resolution',
    'value': 694,
    'score': 694,
    'url': 'https://www.yahoo.com/news/house-democrats-pushing-25th-amendment-154917024.html'},
   {'name': 'Nancy Pelosi Reveals Mitch McConnell Blocked Ruth Bader Ginsburg From Getting Capitol Rotunda Memorial',
    'value': 693,
    'score': 693,
    'url': 'https://www.mediaite.com/news/nancy-pelosi-reveals-mitch-mcconnell-blocked-ruth-bader-ginsburg-from-getting-capitol-rotunda-memorial/'},
   {'name': "Beto O'Rourke promises marijuana legalization after winning Texas governor nomination",
    'value': 689,
    'score': 689,
    'url': 'https://www.kcentv.com/article/news/politics/beto-orourke-promises-marijuana-legalization-after-winning-governor-nomination-takes-on-incumbent-greg-abbott-in-fall/500-b2e485a5-66e7-41c1-b18e-4e84b42993fd'},
   {'name': "Trump's inner circle admits to the Jan. 6 committee: He lost the election, but wanted to overturn it; The panel aired never-before-seen footage of the deadly insurrection and statements from people in the mob saying they came to D.C. at Trump's urging.",
    'value': 688,
    'score': 688,
    'url': 'https://www.nbcnews.com/politics/congress/jan-6-panel-launches-case-trump-slew-allies-refuting-election-lie-rcna32890'},
   {'name': 'Clarence Thomas Told His Clerks He Wants to Make Liberals Miserable',
    'value': 688,
    'score': 688,
    'url': 'https://www.businessinsider.com/clarence-thomas-told-clerks-he-wants-to-make-liberals-miserable-2022-6'},
   {'name': "DOJ points out that Trump's legal filings don't align with his public statements about the Mar-a-Lago records",
    'value': 688,
    'score': 688,
    'url': 'https://www.businessinsider.com/mar-a-lago-doj-trump-legal-filings-dont-align-statements-2022-9#amp_tf=From%20%251%24s&amp;aoh=16631479786045&amp;csi=0&amp;referrer=https%3A%2F%2Fwww.google.com&amp;ampshare=https%3A%2F%2Fwww.businessinsider.com%2Fmar-a-lago-doj-trump-legal-filings-dont-align-statements-2022-9'},
   {'name': 'It looks like some Capitol rioters are taking plea deals and agreeing to sell each other out',
    'value': 679,
    'score': 679,
    'url': 'https://www.insider.com/capitol-rioters-may-be-taking-cooperation-deals-with-federal-prosecutors-2021-2'},
   {'name': 'Almost Twice as Many Republicans Died From COVID Before the Midterms Than Democrats',
    'value': 678,
    'score': 678,
    'url': 'https://www.vice.com/en/article/v7vjx8/almost-twice-as-many-republicans-died-from-covid-before-the-midterms-than-democrats'},
   {'name': 'Trump Has Shocking Moment of Honesty During CPAC Speech, Says Straw Poll Is Only Accurate If It’s Good For Him; If It’s Bad, He’ll ‘Just Say It’s Fake’',
    'value': 677,
    'score': 677,
    'url': 'https://www.mediaite.com/politics/trump-has-shocking-moment-of-honesty-during-cpac-speech-says-if-straw-poll-is-only-accurate-if-its-good-for-him-if-its-bad-hell-just-say-its-fake/'},
   {'name': 'Dad of child with Down’s syndrome confronts Marjorie Taylor Greene over disabled slur, she is a disgusting pathetic human, Republicans are you proud.',
    'value': 673,
    'score': 673,
    'url': 'https://www.independent.co.uk/news/world/americas/us-politics/marjorie-taylor-greene-gop-downs-syndrome-b1801455.html'},
   {'name': 'Herschel Walker, running for U.S. Senate in Georgia, still gets tax break on $3 million Texas residence. Under Texas law, homeowners can claim a homestead exemption only on their primary residence. The Republican Senate candidate registered to vote in Georgia last year.',
    'value': 671,
    'score': 671,
    'url': 'https://www.texastribune.org/2022/11/23/herschel-walker-texas-tax-break/'},
   {'name': 'Majority of Americans in new poll say it would be bad for the country if Trump ran in 2024',
    'value': 669,
    'score': 669,
    'url': 'https://thehill.com/homenews/campaign/566440-majority-of-americans-in-new-poll-say-it-would-be-bad-for-the-country-if'},
   {'name': 'Fox is not news, it’s propaganda',
    'value': 669,
    'score': 669,
    'url': 'https://www.latimes.com/entertainment-arts/business/story/2023-02-27/fox-news-rupert-murdoch-election-fraud-dominion'},
   {'name': 'Florida is tied with Texas for having the most people facing charges linked to the Capitol riot, report says',
    'value': 667,
    'score': 667,
    'url': 'https://www.businessinsider.com/florida-tied-with-texas-for-most-capitol-riot-arrests-report-2021-6'},
   {'name': 'GOP demands right to filibuster after taking it away from Democrats in 2017',
    'value': 664,
    'score': 664,
    'url': 'https://americanindependent.com/republicans-demand-filibuster-60-votes-democratic-senate/'},
   {'name': 'Biden Kills Trump Plan to Take Food Aid Away from Millions; The former president’s heartless proposal would have denied nearly one million school children free meals',
    'value': 663,
    'score': 663,
    'url': 'https://www.rollingstone.com/politics/politics-news/biden-trump-food-stamps-1182095/'},
   {'name': 'Michael Moore On Exiting Donald Trump: “We Are Not Done With Him … He Must Pay For His Actions”',
    'value': 661,
    'score': 661,
    'url': 'https://www.yahoo.com/entertainment/michael-moore-exiting-donald-trump-202326390.html'},
   {'name': "'All of them were saying: Trump sent us' | In first testimony, officers say no confusion about who sparked Capitol riot",
    'value': 658,
    'score': 658,
    'url': 'https://www.wusa9.com/article/news/national/capitol-riots/first-testimony-officers-assaulted-during-capitol-riot-fanone-hodges-cheney-kinzinger-raskin-dunn/65-33aed582-6f45-4f03-9622-1bdb0143809a'},
   {'name': "Ted Cruz's 'Pittsburgh over Paris' campaign shows us just how dumb the Biden years are going to be",
    'value': 653,
    'score': 653,
    'url': 'https://www.yahoo.com/news/ted-cruzs-pittsburgh-over-paris-143300116.html'}]},
 {'name': 'Libertarian',
  'data': [{'name': 'Me thinks, you cannot claim to be a patriot if you’re charging the US Capitol waving confederate flag',
    'value': 74585,
    'score': 74585,
    'url': 'https://www.reddit.com/r/Libertarian/comments/kruyq7/me_thinks_you_cannot_claim_to_be_a_patriot_if/'},
   {'name': 'Texas Valedictorian’s Speech: “I am terrified that if my contraceptives fail me, that if I’m raped, then my hopes and efforts and dreams for myself will no longer be relevant.”',
    'value': 55116,
    'score': 55116,
    'url': 'https://lakehighlands.advocatemag.com/2021/06/lhhs-valedictorian-overwhelmed-with-messages-after-graduation-speech-on-reproductive-rights/'},
   {'name': 'Texas has set up a $10,000 bounty for turning in women who have abortions. What crime is up next for a bounty? Speeding? Gun violations? Pot growing?',
    'value': 28750,
    'score': 28750,
    'url': 'https://www.reddit.com/r/Libertarian/comments/pgi2e0/texas_has_set_up_a_10000_bounty_for_turning_in/'},
   {'name': '\'Turning Point USA\' leader deletes tweet saying he sent "80+ buses full of patriots to D.C. to fight for the president". Turning Point\'s website openly advertised the campaign, offering free bus rides and complimentary hotel rooms to anyone willing to travel to D.C.',
    'value': 25549,
    'score': 25549,
    'url': 'https://www.dailydot.com/debug/charlie-kirk-delete-tweet-buses-capitol/'},
   {'name': 'Fuck Vladimir Putin. Long Live Ukraine.',
    'value': 25215,
    'score': 25215,
    'url': 'https://www.reddit.com/r/Libertarian/comments/t01mcf/fuck_vladimir_putin_long_live_ukraine/'},
   {'name': 'For the Love of God, Can We Please Stop?!',
    'value': 24952,
    'score': 24952,
    'url': 'https://www.reddit.com/r/Libertarian/comments/mhtctg/for_the_love_of_god_can_we_please_stop/'},
   {'name': "Don't Let the Capitol Riot Become a 9/11-Style Excuse for Authoritarianism",
    'value': 22263,
    'score': 22263,
    'url': 'https://reason.com/2021/01/15/dont-let-the-capitol-riot-become-a-9-11-style-excuse-for-authoritarianism/#comments'},
   {'name': 'Dr. Seuss wasn\'t "canceled" and the people who claim he was are fearmongering idiots',
    'value': 22195,
    'score': 22195,
    'url': 'https://www.reddit.com/r/Libertarian/comments/lxtzgg/dr_seuss_wasnt_canceled_and_the_people_who_claim/'},
   {'name': 'Rand Paul: One-third of Republicans will leave party if GOP senators go along with convicting Trump',
    'value': 21916,
    'score': 21916,
    'url': 'https://www.washingtonexaminer.com/news/rand-paul-warns-senate-conviction-will-destroy-gop'},
   {'name': 'Methinks if you’ve defended businesses “rights to religious liberty”, but are outraged by companies removing Parler from app stores and hosting, you are a hypocrite',
    'value': 20581,
    'score': 20581,
    'url': 'https://www.reddit.com/r/Libertarian/comments/ktruz1/methinks_if_youve_defended_businesses_rights_to/'},
   {'name': "Anybody calling for regulations to prevent another gamestop fiasco from happening: don't let them ever tell you that they are for small government again..",
    'value': 20226,
    'score': 20226,
    'url': 'https://www.reddit.com/r/Libertarian/comments/l69rkh/anybody_calling_for_regulations_to_prevent/'},
   {'name': 'If Dems don’t act on marijuana and student loan debt they deserve to lose everything',
    'value': 19846,
    'score': 19846,
    'url': 'https://www.reddit.com/r/Libertarian/comments/rg8lqv/if_dems_dont_act_on_marijuana_and_student_loan/'},
   {'name': 'Joe Biden just stuck to his guns and stood up to the military industrial complex. He took responsibility for the withdrawal and said "the buck stops here." I was surprised by that speech but I am impressed. We are leaving Afghanistan!',
    'value': 19802,
    'score': 19802,
    'url': 'https://www.reddit.com/r/Libertarian/comments/p5oj22/joe_biden_just_stuck_to_his_guns_and_stood_up_to/'},
   {'name': 'The elites don’t want a free market; they want a controlled market that protects their profiteering and keeps you subdued.',
    'value': 19071,
    'score': 19071,
    'url': 'https://mobile.twitter.com/justinamash/status/1354620347325296647'},
   {'name': 'Trump’s legacy: $8 trillion-plus in added debt in one term',
    'value': 17493,
    'score': 17493,
    'url': 'https://www.washingtonexaminer.com/news/trumps-legacy-added-debt-one-term'},
   {'name': "Since 2015, American Police Have Killed 1600% More U.S. Citizens Than 'Mass Shooters'",
    'value': 17453,
    'score': 17453,
    'url': 'https://libertarianinstitute.org/articles/since-2015-american-police-have-killed-1600-more-u-s-citizens-than-mass-shooters/'},
   {'name': "Being so poorly trained that you don't know the difference between a taser and a gun is not a defense for murder",
    'value': 17384,
    'score': 17384,
    'url': 'https://www.nbcnews.com/news/us-news/minnesota-police-chief-says-he-believes-officer-meant-grab-taser-n1263817'},
   {'name': "The U.S. Doesn't Have a Labor Shortage. It Has an Incentive Shortage.",
    'value': 17014,
    'score': 17014,
    'url': 'https://reason.com/2021/05/19/unemployment-benefits-coronavirus-labor-shortage-american-rescue-plan/'},
   {'name': 'Shout-Out to all the idiots trying to prove that the government has to control us',
    'value': 16814,
    'score': 16814,
    'url': 'https://www.reddit.com/r/Libertarian/comments/ot9zow/shoutout_to_all_the_idiots_trying_to_prove_that/'},
   {'name': 'Texas Gov. Greg Abbott, who recently signed a restrictive abortion law, has caught covid and will reportedly receive Regeneron’s monoclonal antibody treatment which was developed with fetal stem cells',
    'value': 16273,
    'score': 16273,
    'url': 'https://thehill.com/homenews/state-watch/568272-abbott-tests-positive-for-covid-19-despite-being-fully-vaccinated'},
   {'name': 'Libertarianism means letting women have the freedom to choose what they do with their own bodies.',
    'value': 16254,
    'score': 16254,
    'url': 'https://www.reddit.com/r/Libertarian/comments/phj1mo/libertarianism_means_letting_women_have_the/'},
   {'name': "Conservatives: It's a private company, they don't have to bake your cake: • Also conservatives: I'm gonna threaten you with State violence if you keep insisting on your private property rights",
    'value': 15954,
    'score': 15954,
    'url': 'https://archive.is/391OB'},
   {'name': "You can't be libertarian and argue that George Floyd dying of a fentanyl overdose absolves a police officer from quite literally crushing his neck while having said overdose.",
    'value': 15913,
    'score': 15913,
    'url': 'https://www.reddit.com/r/Libertarian/comments/m2x4y5/you_cant_be_libertarian_and_argue_that_george/'},
   {'name': 'Denver successfully sent mental health professionals, not police, to hundreds of calls.',
    'value': 14816,
    'score': 14816,
    'url': 'https://www.usatoday.com/story/news/nation/2021/02/06/denver-sent-mental-health-help-not-police-hundreds-calls/4421364001/?fbclid=IwAR1mtYHtpbBdwAt7zcTSo2K5bU9ThsoGYZ1cGdzdlLvecglARGORHJKqHsA'},
   {'name': 'Woman who won’t get vaccinated due to religious beliefs denied kidney transplant',
    'value': 14789,
    'score': 14789,
    'url': 'https://www.independent.co.uk/news/world/americas/covid-vaccine-kidney-transplant-christian-b1934676.html'},
   {'name': 'NOW: Supreme Court overturns Roe v. Wade in landmark opinion',
    'value': 14252,
    'score': 14252,
    'url': 'https://www.foxnews.com/politics/supreme-court-overturns-roe-v-wade-dobbs-v-jackson-womens-health-organization'},
   {'name': "Stop saying Republicans are more likely than Democrats to protect freedom of speech. They don't give a fuck about first amendment rights when it goes against their narrative.",
    'value': 14176,
    'score': 14176,
    'url': 'https://www.reddit.com/r/Libertarian/comments/q7utta/stop_saying_republicans_are_more_likely_than/'},
   {'name': '62 percent say third political party is needed in US',
    'value': 13965,
    'score': 13965,
    'url': 'https://thehill.com/blogs/blog-briefing-room/news/538889-62-percent-say-third-political-party-is-needed-in-us'},
   {'name': "After seeing Zelenskyy be a complete badass in Ukraine I can't help but ask where are these age appropriate candidates in America? I refuse to believe we have zero possible candidates that are under 60 and am realizing even though we have elections they are decided before we even get to vote.",
    'value': 13827,
    'score': 13827,
    'url': 'https://www.reddit.com/r/Libertarian/comments/tetude/after_seeing_zelenskyy_be_a_complete_badass_in/'},
   {'name': 'In France before the revolution in 1789, the 1% owned 35% of the wealth. In America today, the 1% own 32% of the wealth and increasing their share further.',
    'value': 13705,
    'score': 13705,
    'url': 'https://www.reddit.com/r/Libertarian/comments/oe4xby/in_france_before_the_revolution_in_1789_the_1/'},
   {'name': 'Supreme Court has voted to overturn abortion rights, draft opinion shows',
    'value': 13529,
    'score': 13529,
    'url': 'https://www.politico.com/news/2022/05/02/supreme-court-abortion-draft-opinion-00029473'},
   {'name': 'Biden Voter On CNN: “They’re Dropping Bombs In Syria And Those Bombs Are Pretty Expensive For A Guy Who Owes Me $ 2,000”',
    'value': 13059,
    'score': 13059,
    'url': 'https://www.usasupreme.com/biden-voter-on-cnn-theyre-dropping-bombs-in-syria-and-those-bombs-are-pretty-expensive-for-a-guy-who-owes-me-2000-video/'},
   {'name': 'President Joe Biden is reportedly gearing up to issue an executive order compelling the U.S. Federal Trade Commission to draft new “right to repair” rules — a set of regulations that will protect consumers’ ability to repair their equipment on their own and at independent shops.',
    'value': 12340,
    'score': 12340,
    'url': 'https://gizmodo.com/the-biden-administration-is-ready-to-go-to-war-over-ri-1847240802'},
   {'name': "Take the Vaccine or Don't take it, but there is absolutely nothing Libertarian about not respecting the rights of individual property owners to deny access to the unvaccinated.",
    'value': 12310,
    'score': 12310,
    'url': 'https://www.reddit.com/r/Libertarian/comments/r7cgj2/take_the_vaccine_or_dont_take_it_but_there_is/'},
   {'name': 'End civil asset forfeiture. End the drug war. End victimless crimes. End qualified immunity. End the Patriot Act. End FISA 702. End foreign wars. End corporate welfare.',
    'value': 12166,
    'score': 12166,
    'url': 'https://twitter.com/justinamash/status/1351952729091010565?s=20'},
   {'name': 'Biden to ban special bonuses for appointees, expand lobbying prohibitions in new ethics rules - Good news for democracy',
    'value': 11177,
    'score': 11177,
    'url': 'https://www.washingtonpost.com/politics/biden-ethics-administration/2021/01/18/56a9a97a-59bd-11eb-a976-bad6431e03e2_story.html?utm_source=rss&amp;utm_medium=referral&amp;utm_campaign=wp_politics'},
   {'name': 'Dem governor declares COVID-19 emergency ‘over,’ says it’s ‘their own darn fault’ if unvaccinated get sick',
    'value': 11079,
    'score': 11079,
    'url': 'https://www.yahoo.com/news/dem-governor-declares-covid-19-213331865.html'},
   {'name': "Cop Indicted for Leaking Video of Cops Shoving Baton in Man's Mouth Until He Died",
    'value': 10713,
    'score': 10713,
    'url': 'https://thefreethoughtproject.com/good-cop-indicted-for-leaking-video-of-cops-shoving-baton-in-mans-mouth-until-he-died'},
   {'name': "Biden ousting staffers for pot use -- even when they only smoked in states where it's legal: report | Joe Biden's commitment to staff his White House with the best people possible has run head-on into his decades-long support for America's war on drugs.",
    'value': 10698,
    'score': 10698,
    'url': 'https://www.rawstory.com/joe-biden-marijuana/'},
   {'name': 'Trump impeached for inciting US Capitol riots',
    'value': 10557,
    'score': 10557,
    'url': 'https://www.bbc.co.uk/news/world-us-canada-55656385'},
   {'name': "Libertarians To Begin Wearing Masks Now That Government Says They Don't Have To",
    'value': 9717,
    'score': 9717,
    'url': 'https://babylonbee.com/news/libertarians-to-begin-wearing-masks-now-that-government-says-they-dont-have-to?fbclid=IwAR1KTub91CU1jz3K5y8lOyWH1DEfhdsUbYrU1zyU8drLzOxbCFu_xC7dxnE'},
   {'name': 'Whopping 70 percent of unvaccinated Americans would quit their job if vaccines are mandated',
    'value': 9566,
    'score': 9566,
    'url': 'https://thehill.com/changing-america/well-being/prevention-cures/571084-whopping-70-percent-of-unvaccinated-americans'},
   {'name': 'Part of free speech is being criticized for your speech. Deal with it',
    'value': 9494,
    'score': 9494,
    'url': 'https://www.reddit.com/r/Libertarian/comments/ojc2gs/part_of_free_speech_is_being_criticized_for_your/'},
   {'name': 'After suing Mike Lindell, Sidney Powell, and Rudy Giuliani, Dominion says it will go after others who spread claims of election fraud - truth does matter it turns out.',
    'value': 9460,
    'score': 9460,
    'url': 'https://www.businessinsider.com/dominion-voting-systems-machines-mike-lindell-giuliani-election-conspiracy-theory-2021-2?utm_source=reddit.com'},
   {'name': 'At what point do personal liberties trump societies demand for safety?',
    'value': 9326,
    'score': 9326,
    'url': 'https://www.reddit.com/r/Libertarian/comments/pkczh5/at_what_point_do_personal_liberties_trump/'},
   {'name': 'Supreme Court rules 6-3 in allowing border patrol agents to enter any home within 100 miles of the border without warrant. (Court docs in link)',
    'value': 9277,
    'score': 9277,
    'url': 'https://mobile.twitter.com/cristianafarias/status/1534539839529525251?s=20'},
   {'name': "This Gun Shop Says It Won't Do Business With Biden Voters",
    'value': 9010,
    'score': 9010,
    'url': 'https://reason.com/2021/02/12/this-gun-shop-says-it-wont-do-business-with-biden-voters/'},
   {'name': "The Supreme Court's first decision of the day is Kennedy v. Bremerton. In a 6–3 opinion by Gorsuch, the court holds that public school officials have a constitutional right to pray publicly, and lead students in prayer, during school events.",
    'value': 8853,
    'score': 8853,
    'url': 'https://twitter.com/mjs_DC/status/1541423574988234752'},
   {'name': 'Corporations aren\'t "Left leaning or liberal biased"',
    'value': 8841,
    'score': 8841,
    'url': 'https://www.reddit.com/r/Libertarian/comments/kv017e/corporations_arent_left_leaning_or_liberal_biased/'},
   {'name': "AZ House criminal justice committee UNANIMOUSLY passes HB2810 which requires law enforcement to get a criminal conviction BEFORE taking someone's property under civil asset forfeiture",
    'value': 8358,
    'score': 8358,
    'url': 'https://indefenseofliberty.blog/2021/02/17/az-legislature-moves-to-stop-government-theft-of-private-property/'}]},
 {'name': 'centrist',
  'data': [{'name': 'She has a point',
    'value': 936,
    'score': 936,
    'url': 'https://i.redd.it/e30e14q0ei071.jpg'},
   {'name': 'these fools',
    'value': 881,
    'score': 881,
    'url': 'https://i.redd.it/kevupeqrsfz61.png'},
   {'name': 'Centrism',
    'value': 822,
    'score': 822,
    'url': 'https://www.reddit.com/r/centrist/comments/l3njkj/centrism/'},
   {'name': 'Current state of politics ORL',
    'value': 798,
    'score': 798,
    'url': 'https://i.redd.it/xhqzyfe2zul61.jpg'},
   {'name': "Anyone who cannot perceive any difference in police conduct between the killing of George Floyd and the shooting of 16 year old Ma'khia Bryant, ON EITHER SIDE, has been brainwashed.",
    'value': 775,
    'score': 775,
    'url': 'https://www.reddit.com/r/centrist/comments/mx0zq6/anyone_who_cannot_perceive_any_difference_in/'},
   {'name': 'Rare Quadrant Unity? 😳',
    'value': 769,
    'score': 769,
    'url': 'https://i.redd.it/k55tu9hk96e61.jpg'},
   {'name': 'Cognitive dissonance',
    'value': 748,
    'score': 748,
    'url': 'https://i.redd.it/dgn4o779fiq71.jpg'},
   {'name': 'Simpleton post: Violence is violence, your “side” doing it should actually motivate you to condemn it more fiercly',
    'value': 712,
    'score': 712,
    'url': 'https://www.reddit.com/r/centrist/comments/kuzul1/simpleton_post_violence_is_violence_your_side/'},
   {'name': 'The United-States is in desperate need of centrism.',
    'value': 697,
    'score': 697,
    'url': 'https://www.reddit.com/r/centrist/comments/kt855z/the_unitedstates_is_in_desperate_need_of_centrism/'},
   {'name': 'Viral Video: Charles Barkley tells TV audience that politicians want Black people and White people to hate each other so that they can “keep their grasp on money and power.”',
    'value': 656,
    'score': 656,
    'url': 'https://youtu.be/5bbb9L42NHc'},
   {'name': 'Time to touch grass.',
    'value': 652,
    'score': 652,
    'url': 'https://i.redd.it/5jhv2o1knwy71.jpg'},
   {'name': 'Please remember this 🙏🏻',
    'value': 629,
    'score': 629,
    'url': 'https://i.redd.it/875y7aokwkk81.jpg'},
   {'name': 'The current life of a Centrist in the US.',
    'value': 628,
    'score': 628,
    'url': 'https://i.redd.it/uc2jtj1xv0q71.jpg'},
   {'name': 'Don\'t let people pretend the "stop the steal" movement is valid',
    'value': 621,
    'score': 621,
    'url': 'https://www.reddit.com/r/centrist/comments/ktpumk/dont_let_people_pretend_the_stop_the_steal/'},
   {'name': 'Can most people here agree with this?',
    'value': 578,
    'score': 578,
    'url': 'https://i.redd.it/uvzvgjthap281.jpg'},
   {'name': '[deleted by user]',
    'value': 565,
    'score': 565,
    'url': 'https://www.reddit.com/r/centrist/comments/ol59wj/deleted_by_user/'},
   {'name': 'This sub is way more obsessed with race and BLM than any of the left wing subs I visit',
    'value': 561,
    'score': 561,
    'url': 'https://www.reddit.com/r/centrist/comments/n0g12v/this_sub_is_way_more_obsessed_with_race_and_blm/'},
   {'name': 'Black Lives Matter Website Lies About Ma’Khia Bryant Shooting',
    'value': 555,
    'score': 555,
    'url': 'https://www.reddit.com/r/centrist/comments/mzgm75/black_lives_matter_website_lies_about_makhia/'},
   {'name': 'do you think this is in a certain sense the essence of centrism?',
    'value': 549,
    'score': 549,
    'url': 'https://i.redd.it/1anwypeu6mg71.jpg'},
   {'name': 'I think Reddit is officially overran by activists engaging in what Chomskey would call "Manufacturing Consent" - And it\'s wild to watch first hand',
    'value': 540,
    'score': 540,
    'url': 'https://www.reddit.com/r/centrist/comments/pjmyjg/i_think_reddit_is_officially_overran_by_activists/'},
   {'name': 'Anyone else notice that since Donald Trump stopped being president political content on Reddit has dropped?',
    'value': 539,
    'score': 539,
    'url': 'https://www.reddit.com/r/centrist/comments/lgaz4n/anyone_else_notice_that_since_donald_trump/'},
   {'name': 'Friendly reminder that the CCP is an authoritarian regime that has a body count of at least 40 million: Tiananmen Square Massacre footage',
    'value': 537,
    'score': 537,
    'url': 'https://youtu.be/kMKvxJ-Js3A'},
   {'name': "It's okay go ahead and give me the downvotes",
    'value': 534,
    'score': 534,
    'url': 'https://i.redd.it/8pjggctz5ey61.jpg'},
   {'name': 'R/politics is pretty far left',
    'value': 530,
    'score': 530,
    'url': 'https://i.redd.it/wayhvctxbw171.jpg'},
   {'name': 'My final thoughts on POTUS 45, Donald Trump',
    'value': 528,
    'score': 528,
    'url': 'https://www.reddit.com/r/centrist/comments/l1cghh/my_final_thoughts_on_potus_45_donald_trump/'},
   {'name': 'Good advice.',
    'value': 520,
    'score': 520,
    'url': 'https://i.redd.it/38qgpz3jl4181.png'},
   {'name': 'If you truly believe the media is worse for Biden than it was for the Cheeto you are the literal definition of brainwashed.',
    'value': 520,
    'score': 520,
    'url': 'https://i.redd.it/2i68x3wv0fu71.jpg'},
   {'name': 'Ana Kasparian, a huge American progressive political commentator, now hates to be called a "person with a uterus, birthing person, or person who menstruates", as opposed to just being called a woman.',
    'value': 518,
    'score': 518,
    'url': 'https://i.redd.it/jnjbs9w54jpa1.png'},
   {'name': "120 anti-Trump Republicans are in talks to form a center-right 3rd party that would run on 'principled conservatism,' report says",
    'value': 509,
    'score': 509,
    'url': 'https://www.businessinsider.com/anti-trump-republicans-talks-to-form-third-party-reuters-2021-2'},
   {'name': 'BLM Protesters shared a pizzas with Rittenhouse Supporters and spoke of unity outside of Kenosha court house',
    'value': 507,
    'score': 507,
    'url': 'https://v.redd.it/w90s6gpg6d081'},
   {'name': 'Makiyah Bryant... wtf?',
    'value': 507,
    'score': 507,
    'url': 'https://www.reddit.com/r/centrist/comments/mvkyie/makiyah_bryant_wtf/'},
   {'name': 'Gallup Poll: Only 5% of Hispanic Americans prefer the term "Latinx"',
    'value': 506,
    'score': 506,
    'url': 'https://news.gallup.com/poll/353000/no-preferred-racial-term-among-black-hispanic-adults.aspx'},
   {'name': 'As a European looking in, Jan 6 was obviously wrong but people who continue to downplay the summer 2020 riots have absolutely no moral authority here',
    'value': 503,
    'score': 503,
    'url': 'https://www.reddit.com/r/centrist/comments/ot71q9/as_a_european_looking_in_jan_6_was_obviously/'},
   {'name': 'I’m fed up with the absolutism in politics these days.',
    'value': 478,
    'score': 478,
    'url': 'https://www.reddit.com/r/centrist/comments/nsyf9z/im_fed_up_with_the_absolutism_in_politics_these/'},
   {'name': 'Hey moderators, can we change the comment section back to sorted by best please',
    'value': 477,
    'score': 477,
    'url': 'https://www.reddit.com/r/centrist/comments/kwnmkp/hey_moderators_can_we_change_the_comment_section/'},
   {'name': 'I’m not a centrist because my beliefs fall between two parties, I’m a centrist because I stand against the absolutism that is corrupting our nation and relationships. How about you?',
    'value': 471,
    'score': 471,
    'url': 'https://www.reddit.com/r/centrist/comments/nw6gxz/im_not_a_centrist_because_my_beliefs_fall_between/'},
   {'name': "I'm So Fed Up With It All",
    'value': 467,
    'score': 467,
    'url': 'https://www.reddit.com/r/centrist/comments/ksag3y/im_so_fed_up_with_it_all/'},
   {'name': 'Unlike Homosexuality, Bisexuality, Pansexuality and so on, the more you look at Gender-Fluidity/Neutrality, the less it makes sense. And people are right to question it.',
    'value': 465,
    'score': 465,
    'url': 'https://www.reddit.com/r/centrist/comments/oa5sqd/unlike_homosexuality_bisexuality_pansexuality_and/'},
   {'name': "Sometimes it feels like I'm talking to brick walls when it comes to political issues.",
    'value': 462,
    'score': 462,
    'url': 'https://www.reddit.com/r/centrist/comments/m2ld09/sometimes_it_feels_like_im_talking_to_brick_walls/'},
   {'name': 'Stop minimizing the storming of the Capitol Building',
    'value': 457,
    'score': 457,
    'url': 'https://www.reddit.com/r/centrist/comments/ktlq4h/stop_minimizing_the_storming_of_the_capitol/'},
   {'name': 'Only a sith deals in absolutes',
    'value': 451,
    'score': 451,
    'url': 'https://i.redd.it/zxse8c41hpy71.jpg'},
   {'name': 'Why can’t everyone seem to get this?',
    'value': 449,
    'score': 449,
    'url': 'https://i.redd.it/qkmkbirxqpi91.jpg'},
   {'name': "It's pretty amazing how everyone seems to suddenly have an opinion on the Israel-Palestine conflict now",
    'value': 443,
    'score': 443,
    'url': 'https://www.reddit.com/r/centrist/comments/nekb0t/its_pretty_amazing_how_everyone_seems_to_suddenly/'},
   {'name': 'Is “whiteness” a dog whistle for racist POC?',
    'value': 441,
    'score': 441,
    'url': 'https://www.reddit.com/r/centrist/comments/mn5gec/is_whiteness_a_dog_whistle_for_racist_poc/'},
   {'name': 'End Legalized Bribery',
    'value': 435,
    'score': 435,
    'url': 'https://i.redd.it/rsqf1pwiaoea1.jpg'},
   {'name': 'Calvin explaining why politicians don’t run as Centrists',
    'value': 435,
    'score': 435,
    'url': 'https://i.redd.it/fvg57gapw0s71.jpg'},
   {'name': "Thoughts on Biden's 10-day executive actions plan following inauguration?",
    'value': 434,
    'score': 434,
    'url': 'https://i.redd.it/1s8cgj9br4c61.png'},
   {'name': "Dumbass opinions like this is why I won't identify as a liberal despite leaning more to the left for the most part.",
    'value': 434,
    'score': 434,
    'url': 'https://i.redd.it/ia5if8695ij61.jpg'},
   {'name': 'I am in complete shock and disbelief',
    'value': 430,
    'score': 430,
    'url': 'https://www.reddit.com/r/centrist/comments/krv9vg/i_am_in_complete_shock_and_disbelief/'},
   {'name': 'If you took the Israel/Palestine conflict and replaced it with any other military conflict, you’d understand why Israel can’t just call it quits because people asked them to',
    'value': 430,
    'score': 430,
    'url': 'https://www.reddit.com/r/centrist/comments/ng1fs6/if_you_took_the_israelpalestine_conflict_and/'}]},
 {'name': 'socialism',
  'data': [{'name': "You won't hear a better argument for unions than this.",
    'value': 62514,
    'score': 62514,
    'url': 'https://v.redd.it/dlrn6zmwge791'},
   {'name': 'Fuck apartheid, free palestine!',
    'value': 35782,
    'score': 35782,
    'url': 'https://v.redd.it/p0shjic3lds81'},
   {'name': 'This is how you go on Fox News.',
    'value': 35445,
    'score': 35445,
    'url': 'https://v.redd.it/hjfreobyf8e81'},
   {'name': 'Irish Socialist Member of Parliament speaks the truth on parasitic landlords',
    'value': 22983,
    'score': 22983,
    'url': 'https://v.redd.it/qc4agut84qb91'},
   {'name': 'Word on the street in Portland, OR',
    'value': 16419,
    'score': 16419,
    'url': 'https://i.redd.it/wkk0kthooix81.jpg'},
   {'name': 'Man kicked out of McDonald’s after buying food to a homeless elderly',
    'value': 14330,
    'score': 14330,
    'url': 'https://v.redd.it/xi2gkjkybbd91'},
   {'name': "This isn't a parody, nor an SNL skit. This is an actual scene from an American TV show. The narcissism that must have gone into creating this piece of propaganda is bleak.",
    'value': 13291,
    'score': 13291,
    'url': 'https://v.redd.it/wb5brhtlfen91'},
   {'name': 'Remember who the enemy is:',
    'value': 12873,
    'score': 12873,
    'url': 'https://i.redd.it/vbhgnfoi62h81.png'},
   {'name': 'Frito-Lay worker Brandon Ingram was severely electrocuted on the job, disabled and denied medical care. Now Brandon, his wife, and children are being stalked and secretly filmed by company agents. This is the most disturbing Frito-Lay story we’ve covered. @moreperfectus',
    'value': 12792,
    'score': 12792,
    'url': 'https://v.redd.it/sgslc4vjm0i81'},
   {'name': 'I would love to see what a socialist country would look like without interference from the capitalist powers of the world',
    'value': 11363,
    'score': 11363,
    'url': 'https://i.redd.it/fyjlka3rhf961.jpg'},
   {'name': 'Mitch McConnell’s house was vandalized this morning. People are getting angry at congress’s inaction.',
    'value': 11307,
    'score': 11307,
    'url': 'https://i.redd.it/v4fmywypiz861.jpg'},
   {'name': 'Churches should pay taxes.',
    'value': 10639,
    'score': 10639,
    'url': 'https://i.redd.it/pcznu822s8q81.jpg'},
   {'name': '"You are not a capitalist. You are an exploited worker with Stockholm Syndrome" sticker spotted in St Louis, Missouri',
    'value': 10563,
    'score': 10563,
    'url': 'https://i.redd.it/kmqxn6ldcvu61.jpg'},
   {'name': 'Lanlords are leeches',
    'value': 10425,
    'score': 10425,
    'url': 'https://v.redd.it/bwh8wej19ti81'},
   {'name': 'Keep your religion out of my abortion access',
    'value': 9906,
    'score': 9906,
    'url': 'https://v.redd.it/d095d8bdqcx81'},
   {'name': "Meanwhile let's not look at these",
    'value': 9725,
    'score': 9725,
    'url': 'https://i.redd.it/ph0okcy72zj81.jpg'},
   {'name': "Saudi Arabia dropping bombs on Yemen. Definitely won't see this being reported on the nightly news.",
    'value': 9280,
    'score': 9280,
    'url': 'https://v.redd.it/i5dzlc1qfyl81'},
   {'name': 'Israeli police beats a 12 year old girl in East Jerusalem',
    'value': 9258,
    'score': 9258,
    'url': 'https://v.redd.it/q6t1xvv2blk81'},
   {'name': 'Basically my whole family.',
    'value': 9193,
    'score': 9193,
    'url': 'https://i.redd.it/gfw1c71otkd61.jpg'},
   {'name': "Mick Lynch, the head of the British railroad worker's union calls on workers of the UK to unite and demand better conditions for all.",
    'value': 8851,
    'score': 8851,
    'url': 'https://v.redd.it/7nr1fwars0891'},
   {'name': 'Billionaires don’t earn their wealth',
    'value': 8383,
    'score': 8383,
    'url': 'https://i.redd.it/v85tmbqh8oj91.jpg'},
   {'name': 'Berliners after voting to remove corporate landlords and turn 200,000 homes into public housing',
    'value': 8202,
    'score': 8202,
    'url': 'https://v.redd.it/btndew18cyp71'},
   {'name': "Greta Thunberg: It's time to overthrow the West's oppressive and racist capitalist system",
    'value': 8162,
    'score': 8162,
    'url': 'https://www.msn.com/en-gb/entertainment/music/greta-thunberg-its-time-to-overthrow-the-wests-oppressive-and-racist-capitalist-system/ar-AA13Ebby'},
   {'name': "Fighting for Raising Teacher's Pay, 1930s...",
    'value': 7647,
    'score': 7647,
    'url': 'https://i.redd.it/zpilznvnk5e91.png'},
   {'name': 'Happy 39th birthday to comrade Mike Prysner, whose burning hatred for imperialist George W. Bush and the U.S. war machine is an inspiration.',
    'value': 7137,
    'score': 7137,
    'url': 'https://v.redd.it/5zgh9l7r9u591'},
   {'name': "We're f**ked aren't we.",
    'value': 7017,
    'score': 7017,
    'url': 'https://v.redd.it/9419h6j3iof81'},
   {'name': 'We have enough resources to satisfy everybody’s needs, not everybody’s greed.',
    'value': 7015,
    'score': 7015,
    'url': 'https://i.redd.it/ttno4sunmxf91.jpg'},
   {'name': 'Another beloved historical figure who’s politics were conveniently ignored',
    'value': 6960,
    'score': 6960,
    'url': 'https://i.redd.it/qb20td8o3if91.jpg'},
   {'name': 'Irish politician Richard boyd Barett goes off in the government chamber over the hypocrisy of sanctions against Rvssia when Israel has escaped them for over 70 years',
    'value': 6719,
    'score': 6719,
    'url': 'https://v.redd.it/63jhkdwh2cl81'},
   {'name': 'Today, the President of France said he’s going to force through a raise of the retirement age without a vote. Tonight, Paris looks like this.',
    'value': 6678,
    'score': 6678,
    'url': 'https://v.redd.it/wvsvxn74p5oa1'},
   {'name': 'Money and Greed is why',
    'value': 6672,
    'score': 6672,
    'url': 'https://i.redd.it/44uncz6fl5a81.jpg'},
   {'name': 'Palestinian content creator Adnan Barq has gone viral for his hilarious reaction to Israeli forces storming a Palestinian protest in the occupied East Jerusalem',
    'value': 6640,
    'score': 6640,
    'url': 'https://v.redd.it/kibxce735w291'},
   {'name': 'The US will starve your people and then condemn you for not providing',
    'value': 6391,
    'score': 6391,
    'url': 'https://i.redd.it/fbotg228w7b71.jpg'},
   {'name': "6,000 Amazon warehouse workers in Alabama will vote next month on forming the first union in the company's history",
    'value': 6271,
    'score': 6271,
    'url': 'https://www.businessinsider.com/amazon-workers-vote-on-union-2021-1'},
   {'name': 'Don’t become a Doomer. Become a Revolutionary.',
    'value': 6191,
    'score': 6191,
    'url': 'https://i.redd.it/7ibpkjbquz891.jpg'},
   {'name': "In case you're wondering why Catalonian protests aren't covered much, they have the wrong flags",
    'value': 6071,
    'score': 6071,
    'url': 'https://i.redd.it/acfqlzci9ji61.jpg'},
   {'name': 'We are aware what happens when Latin Americans elect leftists, Ted',
    'value': 6067,
    'score': 6067,
    'url': 'https://v.redd.it/pcp14r7bb5h91'},
   {'name': 'A 6 billion pound funeral while 1/4 british cannot afford to turn on the heating this winter.',
    'value': 6004,
    'score': 6004,
    'url': 'https://www.reddit.com/r/socialism/comments/xa2ipc/a_6_billion_pound_funeral_while_14_british_cannot/'},
   {'name': 'Money and Greed is why',
    'value': 5937,
    'score': 5937,
    'url': 'https://i.imgur.com/2dgAHW7.jpg'},
   {'name': 'This is the way: Armed Antifa protects drag brunch in Texas',
    'value': 5913,
    'score': 5913,
    'url': 'https://v.redd.it/mpx1iejfnik91'},
   {'name': 'The US has been robbing Haiti for years.',
    'value': 5872,
    'score': 5872,
    'url': 'https://i.redd.it/njk3ojj7xqp71.png'},
   {'name': 'Modern day Capitalism visualized in under 20 seconds.',
    'value': 5808,
    'score': 5808,
    'url': 'https://v.redd.it/qxbv5453m9k81'},
   {'name': 'Propaganda pic lying about the purpose of this example of Hostile Architecture.',
    'value': 5776,
    'score': 5776,
    'url': 'https://i.redd.it/9l6ejk817kl81.jpg'},
   {'name': 'No war but class war.',
    'value': 5767,
    'score': 5767,
    'url': 'https://i.redd.it/7uhcnfluxsj81.jpg'},
   {'name': 'all the white moderates please stand up',
    'value': 5761,
    'score': 5761,
    'url': 'https://i.redd.it/k1awfvecf9c81.jpg'},
   {'name': 'Vacant Irish Housing Opened to Public by Socialist Republicans',
    'value': 5733,
    'score': 5733,
    'url': 'https://v.redd.it/gjhkj31cuen81'},
   {'name': 'Irish politician Richard Boyd Barett goes off in the government chamber over the hypocrisy of sanctions against Russia when Israel has escaped them for over 70 years',
    'value': 5675,
    'score': 5675,
    'url': 'https://v.redd.it/hgh1svtqg3391'},
   {'name': 'Remember This Next Time They Tell You Something Is Too Expensive',
    'value': 5577,
    'score': 5577,
    'url': 'https://i.redd.it/arwr8y8gfij61.jpg'},
   {'name': 'A man self immolated and died in front of the Supreme Court to protest climate inaction, the media will not even report that it was a protest or why. This is the inhumanity of capitalist media',
    'value': 5512,
    'score': 5512,
    'url': 'https://twitter.com/jeremy_writes/status/1518048418924580865'},
   {'name': 'Fuck you, Mr. President.',
    'value': 5504,
    'score': 5504,
    'url': 'https://i.redd.it/rld5v3fmwic61.jpg'}]}]
});
